version: '3.7'
volumes:
  prometheus_data: {}
  grafana_data: {}
networks:
  monitor-net:
services:
  prometheus:
    image: prom
    build:
      context: .
      dockerfile: Dockerfile.prom
    ports:
      - "9090:9090"
      - "9093:9093"
    networks:
      - monitor-net
    volumes:
      - prometheus_data:/prometheus:Z
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "4000:4000"
    networks:
      - monitor-net
  grafana:
    image: graf
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    volumes:
      - grafana_data:/var/lib/grafana:Z